-- 1. Tablas independientes (Usamos SERIAL para autoincremento en PG)
CREATE TABLE CATEGORIES (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE COUNTRIES (
    ID SERIAL PRIMARY KEY,
    COUNTRY_NAME VARCHAR(150) NOT NULL,
    ISO_CODE CHAR(3) NOT NULL
);

-- 2. Usuarios y Detalles (Relación 1:1)
CREATE TABLE USERS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(50) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    ISVERIFIED BOOLEAN NOT NULL DEFAULT FALSE,
    USER_DETAILS_ID UUID
);

CREATE TABLE USER_DETAILS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    COUNTRY_ID INT,
    USER_ID UUID,
    DIRECTION_1 VARCHAR(150),
    DIRECTION_2 VARCHAR(150),
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- 3. Productos
CREATE TABLE PRODUCTS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    NAME VARCHAR(100) NOT NULL,
    CATEGORY_ID INT,
    STOCK INT CHECK (STOCK >= 0),
    PRICE DECIMAL(10,2) CHECK (PRICE > 0.00),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);

-- 4. Órdenes y Detalles
CREATE TABLE ORDERS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    USER_ID UUID,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TOTAL_AMOUNT DECIMAL(10,2),
    STATUS VARCHAR(25),
    CONSTRAINT CHK_STATUS CHECK (STATUS IN ('PENDING', 'PAID', 'SHIPPED', 'CANCELLED')),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE ORDER_ITEMS (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    ORDER_ID UUID,
    PRODUCT_ID UUID,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
);
